project: free-beer-293221
zone: us-west1-b
cluster_name: slurm
external_compute_ips: false
shared_vpc_host_project: null
compute_node_prefix: slurm-compute
compute_node_service_account: default
compute_node_scopes:
- https://www.googleapis.com/auth/monitoring.write
- https://www.googleapis.com/auth/logging.write
slurm_cmd_path: /apps/slurm/current/bin
log_dir: /var/log/slurm
google_app_cred_path: null
update_node_addrs: null
partitions:
- machine_type: n1-standard-2
  max_node_count: 10
  name: debug
  zone: us-central1-a
  compute_disk_type: pd-standard
  compute_disk_size_gb: 20
  compute_labels: {}
  gpu_count: 0
  preemptible_bursting: false
  static_node_count: 0
  network_storage: []
  region: us-central1
